"""add original price/currency to sales

Revision ID: 2244719f9cf7
Revises: d4fde728c1d8
Create Date: 2026-09-30 17:08:10.399919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2244719f9cf7'
down_revision: Union[str, Sequence[str], None] = 'd4fde728c1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('original_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'original_currency')
    op.drop_column('sales', 'original_price')
    # ### end Alembic commands ###
