"""add supertype and subtypes to cards

Revision ID: d10e53f7df92
Revises: 2244719f9cf7
Create Date: 2026-09-30 23:19:27.745253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10e53f7df92'
down_revision: Union[str, Sequence[str], None] = '2244719f9cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('supertype', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('subtypes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'subtypes')
    op.drop_column('cards', 'supertype')
    # ### end Alembic commands ###
