"""initial schema

Revision ID: d4fde728c1d8
Revises: 
Create Date: 2026-09-30 15:49:46.186771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fde728c1d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('set_id', sa.String(), nullable=False),
    sa.Column('set_name', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('image_small', sa.String(), nullable=True),
    sa.Column('image_large', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cards_card_number', 'cards', ['card_number'], unique=False)
    op.create_index(op.f('ix_cards_external_id'), 'cards', ['external_id'], unique=True)
    op.create_index('ix_cards_name', 'cards', ['name'], unique=False)
    op.create_index('ix_cards_set_id', 'cards', ['set_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latest_sale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_snapshots_card_id', 'price_snapshots', ['card_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('source_sale_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('shipping', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('grading_company', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('listing_type', sa.String(), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('listing_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'source_sale_id', name='uq_sales_provider_source_sale_id')
    )
    op.create_index('ix_sales_card_id', 'sales', ['card_id'], unique=False)
    op.create_index('ix_sales_provider', 'sales', ['provider'], unique=False)
    op.create_index('ix_sales_sold_at', 'sales', ['sold_at'], unique=False)
    op.create_table('tracked_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked_cards')
    op.drop_index('ix_sales_sold_at', table_name='sales')
    op.drop_index('ix_sales_provider', table_name='sales')
    op.drop_index('ix_sales_card_id', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_price_snapshots_card_id', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index('ix_cards_set_id', table_name='cards')
    op.drop_index('ix_cards_name', table_name='cards')
    op.drop_index(op.f('ix_cards_external_id'), table_name='cards')
    op.drop_index('ix_cards_card_number', table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
